Repository mitre/heimdall-vue, pull requests merged in 2019-07, with the labels that each got.

#47 LINT: Downgrade linter and fix several remaining issues
  .eslintrc.js
  src/components/DataTable.vue
  src/components/Treemap.vue
  src/views/Home.vue
Labels: Component, bug, enhancement, lint

#45 Storybook
  .storybook/addons.js
  .storybook/config.js
  .storybook/webpack.config.js
  package-lock.json
  package.json
  stories/MyButton.js
  stories/Welcome.js
  stories/index.stories.js
Labels: enhancement

#63 Added new CountCard component
  src/components/CountCard.vue
  src/views/results.vue
Labels: Component

#71 Vb/countcard
  package-lock.json
  package.json
  src/components/ControlCard.vue
  src/components/CountCard.vue
  src/views/results.vue
  src/views/ui-elements/card/analyticsData.js
  themeConfig.js
Labels: Component, enhancement

#81 Lm/file select lint
  src/components/DataTable.vue
  src/layouts/components/vx-sidebar/FileSelect.vue
Labels: lint

#92 BUG: font family is being overwritten
  src/assets/scss/vuesax/_variables.scss
Labels: bug

#86 Vb/countcard
  package-lock.json
  package.json
  src/assets/scss/vuesax/_variables.scss
  src/components/ComplianceLevelCard.vue
  src/components/ControlCard.vue
  src/components/ControlSeverityCard.vue
  src/components/ControlStatusCard.vue
  src/components/CountCard.vue
  src/layouts/components/TheNavbar.vue
  src/main.ts
  src/store/theme.ts
  src/views/results.vue
  src/views/ui-elements/card/analyticsData.js
Labels: Component, enhancement
